Repository Infomaniak/terraform-provider-infomaniak, pull requests merged in 2025-03, with the labels that each got.

#9 docs: improve docs and examples
  docs/data-sources/kaas.md
  docs/data-sources/kaas_instance_pool.md
  docs/resources/kaas.md
  docs/resources/kaas_instance_pool.md
  examples/kaas-kubeconfig-usage/main.tf
  examples/kaas/main.tf
  examples/kaas/outputs.tf
  examples/kaas/provider.tf
  examples/kaas/variables.tf
Labels: documentation

#8 fix: use provided env variables
  README.md
  internal/provider/provider.go
Labels: bug, go

#11 feat(kaas): properly await instance pool
  internal/apis/kaas/implementation/client.go
  internal/apis/kaas/models.go
  internal/services/kaas/kaas_instance_pool_resource.go
Labels: enhancement, go
